name: Update Index HTML

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Bot Script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: |
          python bot/main.py

      - name: Check for Changes
        id: check_changes
        run: |
          changes=$(git status --porcelain | grep -E "index.html|public/data/posts.json")
          if [ -z "$changes" ]; then
            echo "No changes detected."
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected: $changes"
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and Push Changes
        if: steps.check_changes.outputs.changes_detected == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.html public/data/posts.json
          git commit -m "Update index.html and posts data with latest content"
          git push
